project:
  type: website
  output-dir: docs

website:
  title: "ThomasHSimm"
  favicon: /posts/Picture3.png
  body-header: <img src="/posts/header2.png" height=200>
  sidebar:
    contents:
      - section: "About"
        contents:
        - about.qmd
      - section: "Projects"
        contents:
        - text: Ok
          href: /posts/NeuralNetworksMaths.html
      - section: "Guides"
        contents:
        - text: Neural Networks Maths
          href: /posts/NeuralNetworksMaths.html
        - text: TensorFlow
          href: /posts/Tensorflow.html
        - text: SQL
          href: /posts/SQL.html
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/ThomasHSimm
      - icon: twitter
        href: https://twitter.com/ThomasHSimm
format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css



